### ISSUE TITLE
Downscroll breaks held notes

### ISSUE THREAD

**Issue by Leather128** [rayanmargham/FNF-Godot-Engine#14]
(start of bopeebo on hard) 
![image](https://user-images.githubusercontent.com/81660872/144727182-7c1aa32d-bf37-4e4f-8cc6-ad4cab521ab4.png)

You can still hit the held notes, but they are invisible.

**Comment by rayanmargham** [comment]
This is a arrow system issue so I'll get my friend codist on it.

**Comment by rayanmargham** [comment]
feel free to try and fix it yourself and merge it into main if you feel like so

**Comment by Leather128** [comment]
i've been trying, just decided to put an issue up since it seems hard to fix for me (i'm pretty new to godot tho so i feel it's prolly a lack of experience for me)
