### ISSUE TITLE
keybinds bug

### ISSUE THREAD

**Issue by juliuwu** [rayanmargham/FNF-Godot-Engine#16]
On the Freeplay and settings menu, the keys binds don't work correctly, on the arrows just the up and right work, for some reason the left and down just work on the 'a' and 's' bonds respectively

**Comment by rayanmargham** [comment]
Yes I know this issue for a very long time now I cant exactly figure out what's causing it at the moment but it will be fixed in version 2.0 of the engine

**Comment by juliuwu** [comment]
Ok bro

**Comment by HypnoDevelopment** [comment]
Nah bro too sussy of a bug to fix

**Comment by rayanmargham** [comment]
fixed in latest pr
