### ISSUE TITLE
If you change the downscroll setting mid song, all the arrows go upside-down.

### ISSUE THREAD

**Issue by Leather128** [rayanmargham/FNF-Godot-Engine#9]
![image](https://user-images.githubusercontent.com/81660872/144145991-ae84ab34-1676-4a40-847a-3032fac05cf5.png)

This could probably be fixed by either: Actually changing the scroll mid song or just storing the downscroll value when the song starts, and using that instead of the current actual value (by the way, I'm very new to Godot so I'm not sure if this is really possible, but it was the first thing I could think of).

**Comment by rayanmargham** [comment]
I'll review this tomorrow

**Comment by rayanmargham** [comment]
Just gonna close this
